services:
    app_bundle.twig_database_loader:
        class: AppBundle\Templating\TwigDatabaseLoader
        arguments: [ "@as3_modlr.store" ]

    app_bundle.twig_chain_loader:
        class: Twig_Loader_Chain
        calls:
            - [ addLoader, [ "@app_bundle.twig_database_loader" ] ]
            - [ addLoader, [ "@twig.loader" ] ]

    app_bundle.templating.template_loader:
        class: AppBundle\Templating\TemplateLoader
        arguments:
            - "@as3_modlr.store"
            - "@templating"
            - "@app_bundle.serializer.public_api"

    app_bundle.notification_factory.default:
        private: true
        class: AppBundle\Notifications\NotificationFactory\DefaultFactory

    app_bundle.notification_factory.account.activate:
        private: true
        class: AppBundle\Notifications\NotificationFactory\Account\Activate

    app_bundle.notification_factory.account.reset_password:
        private: true
        class: AppBundle\Notifications\NotificationFactory\Account\ResetPassword

    app_bundle.notification_factory.account.reset_password_generate:
        private: true
        class: AppBundle\Notifications\NotificationFactory\Account\ResetPasswordGenerate

    app_bundle.notification_factory.account_email.verify_generate:
        private: true
        class: AppBundle\Notifications\NotificationFactory\AccountEmail\VerifyGenerate

    app_bundle.notification_factory.product_email_deployment.opt_in:
        private: true
        class: AppBundle\Notifications\NotificationFactory\ProductEmailDeployment\OptIn

    app_bundle.notifications.manager:
        class: AppBundle\Notifications\NotificationManager
        arguments:
            - "@app_bundle.notification_factory.default"
            - "@mailer"
            - "@app_bundle.templating.template_loader"
            - "@app_bundle.core.account_manager"
        calls:
            - [ addFactory, [ "@app_bundle.notification_factory.account.activate" ] ]
            - [ addFactory, [ "@app_bundle.notification_factory.account.reset_password" ] ]
            - [ addFactory, [ "@app_bundle.notification_factory.account.reset_password_generate" ] ]
            - [ addFactory, [ "@app_bundle.notification_factory.account_email.verify_generate" ] ]
            - [ addFactory, [ "@app_bundle.notification_factory.product_email_deployment.opt_in" ] ]

    app_bundle.notifications.resend_command:
        class: AppBundle\Command\Notifications\ResendCommand
        arguments:
            - "app:notifications:resend"
            - "@app_bundle.notifications.manager"
            - "@app_bundle.core.account_manager"
            - "@as3_modlr.store"
            - "@mailer"
            - "@swiftmailer.transport.real"
        tags:
            -  { name: "console.command" }
