# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        core_user:
            id: app_bundle.security.user_provider.core_user
        identity:
            id: app_bundle.security.user_provider.identity
        in_memory:
            memory: ~

    encoders:
        AppBundle\Security\User\CoreUser:
            algorithm: bcrypt
            cost: 13
        AppBundle\Security\User\Account:
            algorithm: bcrypt
            cost: 10

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            context: application
            pattern: ^/app
            provider: identity
            anonymous: ~
            guard:
                authenticators:
                    - app_bundle.security.authenticator.identity
            remember_me:
                secret: "%secret%"
                lifetime: 63072000
                name: __radix-application
                always_remember_me: true
            logout:
                path: /app/auth/destroy
                # delete_cookies: ~ # @todo Will need to determine if identity cookies need deletion?
                invalidate_session: false
                success_handler: app_bundle_security.logout_success_handler.application
        api:
            context: core
            pattern: ^/api\/1\.0
            provider: core_user
            guard:
                authenticators:
                    - app_bundle.security.authenticator.api
        main:
            context: core
            anonymous: ~
            provider: core_user
            guard:
                authenticators:
                    - app_bundle.security.authenticator.core_user
            remember_me:
                secret: "%secret%"
                lifetime: 432000
                name: __radix-core
                always_remember_me: true
            logout:
                path: /auth/user/destroy
                # delete_cookies: ~ # @todo Will need to determine if identity cookies need deletion?
                invalidate_session: false
                success_handler: app_bundle_security.logout_success_handler

    access_control:
        - { path: ^/api/1\.0, roles: [ ROLE_CORE\USER ] }
