# FRONT-END APPLICATION ROUTES #
app_bundle_app_auth_destroy:
    path: /app/auth/destroy
    methods: [ GET ]

app_bundle_app_auth_retrieve:
    path: /app/auth
    defaults: { _controller: AppBundle:App\Auth:retrieve }
    methods: [ GET ]

app_bundle_app_auth_submit:
    path: /app/auth
    methods: [ POST ]

app_bundle_app_auth_verify_reset_token:
    path: /app/auth/verify-reset-token/{token}
    defaults: { _controller: AppBundle:App\Auth:verifyResetToken }
    methods: [ GET ]

app_bundle_app_init:
    path: /app/init
    defaults: { _controller: AppBundle:App\Init:default }
    methods: [ GET ]

app_bundle_app_optins_email_deployment:
    path: /app/opt-ins/email-deployment/{emailAddress}
    defaults: { _controller: AppBundle:App\OptIn:emailDeployment, emailAddress: null }
    methods: [ GET ]

app_bundle_app_product:
    path: /app/product/{type}
    defaults: { _controller: AppBundle:App\Product:all, type: null }
    methods: [ GET ]

app_bundle_app_product_key_or_id:
    path: /app/product/{type}/{keyOrId}
    defaults: { _controller: AppBundle:App\Product:retrieve }
    methods: [ GET ]

app_bundle_app_question_by_tag:
    path: /app/question/tag/{tagKeyOrId}
    defaults: { _controller: AppBundle:App\Question:retrieveByTag }
    methods: [ GET ]

app_bundle_app_question:
    path: /app/question/{keyOrId}
    defaults: { _controller: AppBundle:App\Question:retrieve }
    methods: [ GET ]

app_bundle_app_submission:
    path: /app/submission/{sourceKey}
    defaults: { _controller: AppBundle:App\Submission:index }
    methods: [ GET, POST ]

app_bundle_app_util_country_options:
    path: /app/util/country-options
    defaults: { _controller: AppBundle:App\Utility:countryOptions }
    methods: [ GET ]

app_bundle_app_util_region_options:
    path: /app/util/region-options/{countryCode}
    defaults: { _controller: AppBundle:App\Utility:regionOptions }
    methods: [ GET ]

# LIBRARY ROUTES #

app_bundle_lib:
    path: /lib/{name}.{_format}
    defaults: { _controller: AppBundle:App\Library:index, minify: false }
    requirements:
        _format: css|js

app_bundle_lib_min:
    path: /lib/{name}.min.{_format}
    defaults: { _controller: AppBundle:App\Library:index, minify: true }
    requirements:
        _format: css|js


# CORE RELATED ROUTES #

app_bundle_auth_user_create:
    path: /auth/user/create
    defaults: { _controller: AppBundle:Auth:userCreate }
    methods: [ POST ]

app_bundle_auth_user_destroy:
    path: /auth/user/destroy

app_bundle_auth_user_retrieve:
    path: /auth/user/retrieve
    defaults: { _controller: AppBundle:Auth:userRetrieve }

app_bundle_auth_user_submit:
    path: /auth/user/submit
    methods: [ POST ]

app_bundle_sandbox:
    path: /
    defaults: { _controller: AppBundle:Sandbox:index, path: null, _format: html }

app_bundle_manage:
    path: /manage{path}
    defaults: { _controller: AppBundle:Manage:index, path: '' }
    requirements:
        path: .*

app_bundle_sandbox_sections:
    path: /{path}
    defaults: { _controller: AppBundle:Sandbox:index, _format: html }

