services:
    app_bundle.subscriber_factory_manager:
        class: AppBundle\Factory\SubscriberFactoryManager
        calls:
            - [ addFactory, [ "@app_bundle.factory.identity.account" ] ]
            - [ addFactory, [ "@app_bundle.factory.identity.answer" ] ]
            - [ addFactory, [ "@app_bundle.factory.identity.account_email" ] ]
            - [ addFactory, [ "@app_bundle.factory.identity.external" ] ]
            - [ addFactory, [ "@app_bundle.factory.identity.internal" ] ]
            - [ addFactory, [ "@app_bundle.factory.input_submission" ] ]
            - [ addFactory, [ "@app_bundle.factory.input_answer" ] ]

    app_bundle.factory.identity.account_credentials:
        private: true
        class: AppBundle\Factory\Identity\AccountCredentialsFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.identity.account_credential_password", "@app_bundle.factory.identity.account_credential_social" ]

    app_bundle.factory.identity.account_credential_password:
        private: true
        class: AppBundle\Factory\Identity\AccountCredentialPasswordFactory
        arguments: [ "@as3_modlr.store", "@security.password_encoder", "@app_bundle.security.auth.schema" ]

    app_bundle.factory.identity.account_credential_social:
        private: true
        class: AppBundle\Factory\Identity\AccountCredentialSocialFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.identity.account_email:
        private: true
        class: AppBundle\Factory\Identity\AccountEmailFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.identity.email_verify.token_generator", "@app_bundle.security.auth.schema" ]

    app_bundle.factory.identity.account:
        private: true
        class: AppBundle\Factory\Identity\IdentityInternalFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.identity.address", "@app_bundle.factory.identity.phone", "@app_bundle.factory.identity.answer", "@app_bundle.factory.identity.account_credentials", "@app_bundle.factory.identity.account_email" ]

    app_bundle.factory.identity.external:
        private: true
        class: AppBundle\Factory\Identity\IdentityInternalFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.identity.address", "@app_bundle.factory.identity.phone", "@app_bundle.factory.identity.answer", "@app_bundle.factory.identity.email" ]

    app_bundle.factory.identity.internal:
        private: true
        class: AppBundle\Factory\Identity\IdentityInternalFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.identity.address", "@app_bundle.factory.identity.phone", "@app_bundle.factory.identity.answer", "@app_bundle.factory.identity.email" ]

    app_bundle.factory.identity.address:
        private: true
        class: AppBundle\Factory\Identity\IdentityAddressFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.identity.answer:
        private: true
        class: AppBundle\Factory\Identity\IdentityAnswerFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.question.answer_factory" ]

    app_bundle.factory.identity.email:
        private: true
        class: AppBundle\Factory\Identity\IdentityEmailFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.identity.phone:
        private: true
        class: AppBundle\Factory\Identity\IdentityPhoneFactory
        arguments: [ "@as3_modlr.store" ]

    app_bundle.factory.input_answer:
        private: true
        class: AppBundle\Factory\InputAnswerFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.question.answer_factory" ]

    app_bundle.factory.input_submission:
        private: true
        class: AppBundle\Factory\InputSubmissionFactory
        arguments: [ "@as3_modlr.store", "@app_bundle.factory.input_answer", "@request_stack", "@app_bundle.data_formatter.mongo_db" ]

    app_bundle.factory.product.email_deployment_optin:
        private: true
        class: AppBundle\Factory\ProductEmailDeploymentOptinFactory
        arguments: [ "@as3_modlr.store" ]
