services:
    app_bundle.submission.manager:
        class: AppBundle\Submission\SubmissionManager
        arguments: [ "@app_bundle.factory.input_submission", "@app_bundle.customer.manager", "@app_bundle.notifications.manager" ]
        calls:
            - [ addHandler,  [ "@app_bundle.submission.handler.customer_account" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.customer_account.password_reset_generate" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.customer_email.verify_submit" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.customer_email.verify_generate" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.email_opt_in" ] ]
            - [ addHandler,  [ "@app_bundle.submission.handler.inquiry" ] ]

    app_bundle.submission.handler.customer_account:
        class: AppBundle\Submission\Handlers\CustomerAccountHandler
        arguments: [ "@app_bundle.factory.customer.account" ]

    app_bundle.submission.handler.customer_account.password_reset_generate:
        class: AppBundle\Submission\Handlers\CustomerAccountResetPasswordGenerateHandler
        arguments: [ "@app_bundle.factory.customer.account", "@app_bundle.security.user_provider.customer", "@app_bundle.customer.password_reset.token_generator" ]

    app_bundle.submission.handler.customer_email.verify_generate:
        class: AppBundle\Submission\Handlers\CustomerEmailVerifyGenerateHandler
        arguments: [ "@app_bundle.factory.customer.email" ]

    app_bundle.submission.handler.customer_email.verify_submit:
        class: AppBundle\Submission\Handlers\CustomerEmailVerifySubmitHandler
        arguments: [ "@app_bundle.customer.email_verify.token_generator", "@app_bundle.customer.manager" ]

    app_bundle.submission.handler.email_opt_in:
        class: AppBundle\Submission\Handlers\EmailOptInHandler
        arguments: [ "@app_bundle.factory.product.email_deployment_optin" ]

    app_bundle.submission.handler.inquiry:
        class: AppBundle\Submission\Handlers\InquiryHandler
